export const GOSSIP_CREATED = 'GOSSIP_CREATED';
export const GOSSIPS_FETCHED = 'GOSSIPS_FETCHED';
export const GOSSIPS_RECIVED = 'GOSSIPS_RECIVED';
export const GOSSIP_CREATION_CONFIRMED = 'GOSSIP_CREATION_CONFIRMED';
