export const GOSSIP_CREATED = 'GOSSIP_CREATED';
export const GOSSIPS_FETCHED = 'GOSSIPS_FETCHED';
export const GOSSIPS_RECIVED = 'GOSSIPS_RECIVED';
export const GOSSIP_CREATION_CONFIRMED = 'GOSSIP_CREATION_CONFIRMED';
export const GOSSIP_DELETED = 'GOSSIP_DELETED';
export const GOSSIP_DELETION_CONFIRMED = 'GOSSIP_DELETION_CONFIRMED';
export const GOSSIP_DESCRIPTION_FETCHED = 'GOSSIP_DESCRIPTION_FETCHED';
export const GOSSIP_DESCRIPTION_RECIVED = 'GOSSIP_DESCRIPTION_RECIVED';
